# This file was auto-generated by cabal2nix. Please do NOT edit manually!
# (haha)

{ pkgs ? import <nixpkgs> {}
, haskellPackages ? pkgs.haskellPackages
}:

haskellPackages.cabal.mkDerivation (self: {
  pname = "yapp";
  version = "0.1.0.0";
  src = pkgs.nix-gitignore.gitignoreSource [
    "*.nix"
  ] ./.;
  isLibrary = true;
  buildDepends = [
    haskellPackages.semigroupoids
    haskellPackages.semigroups
  ];
  meta = {
    homepage = "https://github.com/bb010g/yapp";
    description = "Yet Another Polymorphic Prelude";
    license = self.stdenv.lib.licenses.0bsd;
    platforms = self.ghc.meta.platforms;
  };
})
