# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ pkgs ? (import <nixpkgs> {})
, haskellPackages ? pkgs.haskellPackages
}:

haskellPackages.cabal.mkDerivation (self: {
  pname = "yapp";
  version = "0.1.0.0";
  src = /home/brayden/Dropbox/Code/yapp;
  isLibrary = true;
  buildDepends = with haskellPackages; [ semigroupoids ];
  meta = {
    homepage = "https://github.com/bb010g/yapp";
    description = "Yet Another Polymorphic Prelude";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
